version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/server"
    schedule:
      interval: "monthly"
